### PR TITLE
Manip singleton

### PR DESCRIPTION
**Pull request by Manjushriug**
Problem:

Re Initialize Arm and Carousel with new Hardware Map in tele op mode.

Solution:

Move the initialization of the motors from constructor to instance methods.

Test:
1. Build to check for compile errors.
2.  Test on robot to check for arm extension and Carousel functionality.

### CODE REVIEW

**Comment by bignaczak** [comment]
I reviewed the changes and merged them into the master branch.  There were still some issues with the arm when switching opmodes, which I believe were related to Arm maintaining a handle to both opMode and hardwareMap.  These assignments were moved to the init method.

**Comment by bignaczak** [comment]
This is cool, I like these pull requests.  I didn't execute it correctly
though.  I did merge the changes but didn't document it correctly

**Comment by bignaczak** [comment]
Why didn't you include the Bucket in the initManips function?

**Comment by Manjushriug** [comment]
Hmmm...thought of it. But then it was working fine, thought of excuding it.
I think we can move it along with other manips.

**Pull request closed without merging**
